#!/usr/bin/env bash

echo '
Autor ----------------> Inukaze ( Venezuela )
Sitio ----------------> https://goo.gl/ij6WqW
Correo-E -------------> bloginukaze@gmail.com
Licencia -------------> GPL 2

******* Inicio : Acerca de este guión ******** 

 Es para Descargar, Optimizar
 Configurar y Compilar "Automaticamente"
 el emulador de Sony PlayStation 1
 de Software Libre llamado "PCSXReloaded"

 Este guión compilara la version estable
 Actualmente la "1.9.94" + Parches.
******** Fin : Acerca de este guión **********'
sleep 3

if [ "$(whoami)" != root ]; then

	echo
	echo
	echo 'Por favor ejecuta este guion como SuperUsuario (root)'
	echo
	echo 'Utilize este Script bajo su Propio Riesgro'
	echo 'El Autor , o sea yo , no me hago responsable'
	echo 'de las consecuencias imprevistas que puedan'
	echo 'acontecer en tu sistema operativo'
	echo
else
# Obtener la Arquitectura
Arquitectura=$(uname -m)
case "$Arquitectura" in
	x86)    Arquitectura="x32"						;;
	i?86)   Arquitectura="x32"						;;
	amd64)  Arquitectura="x64"						;;
	x86_64) Arquitectura="x64"						;;
	* ) echo    "Tu Arquitectura '$Arquitectura' -> NO ESTA SOPORTADA."	;;
esac

#Definir Variables :
PREFIJO="/opt/videojuegos/emuladores/pcsxr"

#Crear directorios
mkdir -p /tmp/src 
mkdir -p "$PREFIJO"
cd /tmp/src

#Descargar pcsxr + parches
wget -c "http://cdn-fastly.deb.debian.org/debian/pool/main/p/pcsxr/pcsxr_1.9.94.orig.tar.xz"

#Extraer paquetes :
tar xf pcsxr_1.9.94.orig.tar.xz

#Ingresar al directorio del codigo fuente de pcsxr
cd pcsxr

#Descargar parches del repositorio de debian : 
wget -c "http://cdn-fastly.deb.debian.org/debian/pool/main/p/pcsxr/pcsxr_1.9.94-4.debian.tar.xz"

#Extraer parches
tar xf pcsxr_1.9.94-4.debian.tar.xz

#Darles permisos a las carpetas
su -c "chmod 777 -R /tmp/src/pcsxr" root

#aplicando parches
echo "Parche 01" ; patch -p1 < "debian/patches/01_fix-i386-exec-stack.patch"
echo "Parche 02" ; patch -p1 < "debian/patches/02_disable-ppc-auto-dynarec.patch"
echo "Parche 03" ; patch -p1 < "debian/patches/03_fix-plugin-dir.patch"
echo "Parche 04" ; patch -p1 < "debian/patches/04_update-homedir-symlinks.patch"
echo "Parche 05" ; patch -p1 < "debian/patches/05_format-security.patch"
echo "Parche 06" ; patch -p1 < "debian/patches/06_warnings.patch"
echo "Parche 07" ; patch -p1 < "debian/patches/07_non-linux-ip-addr.patch"
echo "Parche 08" ; patch -p1 < "debian/patches/08_reproducible.patch"
echo "Parche 09" ; patch -p1 < "debian/patches/09_zlib-1.2.9.patch"
echo "Parche 10" ; patch -p1 < "debian/patches/10_cross.patch"

# Establecer Optimizaciones
if [ "$Arquitectura" = "x64" ]; then
	export {C,CXX}FLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
fi
if [ "$Arquitectura" = "x32" ]; then
	export {C,CXX}FLAGS='-O2 -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -march=native -mtune=native -pipe'
fi

# Configurar
./autogen.sh
./configure --prefix="$PREFIJO" --libdir="$PREFIJO" --mandir="$PREFIJO" --sysconfdir="$PREFIJO" --localstatedir="$PREFIJO" --enable-opengl  --enable-libcdio 
#
#--enable-dynarec=x86 : por alguna razon termina en "error 1". de todas maneras si ves el error :
#
#"pcsxr: ../libpcsxcore/ix86_64/ix86-64.c:160: MEMADDR_OP: La declaración `!isreg || reg != X86_TEMP' no se cumple." 
# Solo debes activar la opcion "CPU -> CPU Interprete" para poder jugar
#
#--enable-ccdda #cdda : este soporte ha sido excluido / desactivo, ya que al activarla no compila.

# Compilar:
make all

# Instalar
make install ; chmod 777 "$PREFIJO"

# Emulador e Icono
chmod a+o+x "$PREFIJO"/bin/pcsxr
echo
echo "Concede acceso para establecer el icono del menu"
echo
rm -rf /usr/share/pixmaps/pcsxr-icon.png
cp $PREFIJO/share/pixmaps/pcsxr-icon.png /usr/share/pixmaps/pcsxr-icon.png

# Crear el guión lanzador :
echo '#!/usr/bin/env bash

# Establecer Ruta :
PREFIJO='"$PREFIJO"'

# Borrar archivos anteriores :
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFInput"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFNet"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFSound"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
rm -rf "$HOME/.pcsxr/plugins/libBladeSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libDFCdrom.so"
rm -rf "$HOME/.pcsxr/plugins/libDFInput.so"
rm -rf "$HOME/.pcsxr/plugins/libDFNet.so"
rm -rf "$HOME/.pcsxr/plugins/libDFSound.so"
rm -rf "$HOME/.pcsxr/plugins/libDFXVideo.so"
rm -rf "$HOME/.pcsxr/plugins/libNullSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Enlazar Complementos
# Correspondientes a esta version :
ln -sf "$PREFIJO/games/psemu/cfgBladeSio1"	"$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
ln -sf "$PREFIJO/games/psemu/cfgDFCdrom"	"$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
ln -sf "$PREFIJO/games/psemu/cfgDFInput"	"$HOME/.pcsxr/plugins/cfg/cfgDFInput"
ln -sf "$PREFIJO/games/psemu/cfgDFNet"		"$HOME/.pcsxr/plugins/cfg/cfgDFNet"
ln -sf "$PREFIJO/games/psemu/cfgDFSound"	"$HOME/.pcsxr/plugins/cfg/cfgDFSound"
ln -sf "$PREFIJO/games/psemu/cfgDFXVideo"	"$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
ln -sf "$PREFIJO/games/psemu/cfgpeopsxgl"	"$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
ln -sf "$PREFIJO/games/psemu/libBladeSio1.so"	"$HOME/.pcsxr/plugins/libBladeSio1.so"
ln -sf "$PREFIJO/games/psemu/libDFCdrom.so"	"$HOME/.pcsxr/plugins/libDFCdrom.so"
ln -sf "$PREFIJO/games/psemu/libDFInput.so"	"$HOME/.pcsxr/plugins/libDFInput.so"
ln -sf "$PREFIJO/games/psemu/libDFNet.so"	"$HOME/.pcsxr/plugins/libDFNet.so"
ln -sf "$PREFIJO/games/psemu/libDFSound.so"	"$HOME/.pcsxr/plugins/libDFSound.so"
ln -sf "$PREFIJO/games/psemu/libDFXVideo.so"	"$HOME/.pcsxr/plugins/libDFXVideo.so"
ln -sf "$PREFIJO/games/psemu/libNullSio1.so"	"$HOME/.pcsxr/plugins/libNullSio1.so"
ln -sf "$PREFIJO/games/psemu/libpeopsxgl.so"	"$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Iniciar Emulador
export PATH="$PREFIJO/bin/":$PATH
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PREFIJO/games/psemu/"
cd "$PREFIJO/bin"
./pcsxr "$@"
echo' | tee "/tmp/pcsxr"

mv /tmp/pcsxr /usr/bin/pcsxr
chmod a+o+x /usr/bin/pcsxr

#Crear Entrada para el Menú :
echo '[Desktop Entry]
Version=1.0
Type=Application
Name=PCSXR
GenericName=PlayStation Emulator
GenericName[ru_RU]=Эмулятор PlayStation
GenericName[zh_CN]=PlayStation 模拟器
GenericName[zh_TW]=PlayStation 模擬器
Comment=Sony PlayStation emulator
Comment[ru_RU]=Эмулятор Sony PlayStation
Comment[zh_CN]=Sony PlayStation 模拟器
Comment[zh_TW]=Sony PlayStation 模擬器
Comment[es_ES]=Emulador de Sony PlayStation 1
Comment[es_VE]=Emulador de Sony PlayStation 1
Exec=/usr/bin/pcsxr
Icon=pcsxr-icon
Categories=Game;' | sudo tee /usr/share/applications/pcsxr.desktop

echo
echo "Concede acceso de usuario a la entrada de menu"
echo
chmod a+o+x /usr/share/applications/pcsxr.desktop
fi