#!/usr/bin/env bash

echo '
Autor ----------------> Inukaze ( Venezuela )
Sitio ----------------> https://goo.gl/ij6WqW
Correo-E -------------> bloginukaze@gmail.com
Licencia -------------> GPL 2

******* Inicio : Acerca de este guión ******** 

 Es para Descargar, Optimizar
 Configurar y Compilar "Automaticamente"
 el emulador de Sony PlayStation 1
 de Software Libre llamado "PCSXReloaded"

 Este guión compilara la version 
 en desarrollo de este emulador
 
******** Fin : Acerca de este guión **********
'
sleep 3

if [ "$(whoami)" != root ]; then

	echo
	echo
	echo 'Por favor ejecuta este guion como SuperUsuario (root)'
	echo
	echo 'Utilize este Script bajo su Propio Riesgro'
	echo 'El Autor , o sea yo , no me hago responsable'
	echo 'de las consecuencias imprevistas que puedan'
	echo 'acontecer en tu sistema operativo'
	echo
else
# Obtener la Arquitectura
Arquitectura=$(uname -m)
case "$Arquitectura" in
	x86)    Arquitectura="x32"						;;
	i?86)   Arquitectura="x32"						;;
	amd64)  Arquitectura="x64"						;;
	x86_64) Arquitectura="x64"						;;
	* ) echo    "Tu Arquitectura '$Arquitectura' -> NO ESTA SOPORTADA."	;;
esac

#Definir Variables :
#PREFIJO="/usr"	#NOTA puede usar el directorio -> /usr/lib/x86_64-linux-gnu/games/psemu | Para colocar los complementos.
PREFIJO="/opt/videojuegos/emuladores/pcsxr/git"

#Crear directorios
mkdir -p /tmp/src 
mkdir -p "$PREFIJO"
cd /tmp/src

#Descargar (Requiere git preinstalado)
git clone https://github.com/iCatButler/pcsxr

#Ingresar al directorio del codigo fuente de pcsxr
cd pcsxr

# Establecer Optimizaciones
if [ "$Arquitectura" = "x64" ]; then
	export {C,CXX}FLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -fPIC -march=native -mtune=native -pipe'
fi
if [ "$Arquitectura" = "x32" ]; then
	export {C,CXX}FLAGS='-O2 -march=native -mtune=native -pipe'
	export OPTFLAGS='-O2 -march=native -mtune=native -pipe'
fi

# Compilar:
mkdir build ; cd build
cmake -DENABLE_CCDDA:BOOL="1" -DUSE_LIBARCHIVE:BOOL="1" -DUSE_LIBCDIO:BOOL="1" -DBUILD_SIO1:BOOL="1" -DCMAKE_INSTALL_PREFIX:PATH="$PREFIJO" -DCMAKE_BUILD_TYPE=Debug ..
make

# Instalar
make install ; chmod 777 -R "$PREFIJO"

# Si el prefijo es /usr, puede instalar los archivos : 
#borrar#rm -rf /usr/bin/pcsxr
#borrar#rm -rf /usr/share/applications/pcsxr.desktop
#borrar#rm -rf /usr/share/icons/hicolor/48x48/apps/pcsxr-icon.png
#borrar#rm -rf /usr/share/locale/es/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/fr/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/hu/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/it/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/ko_KR/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/pt_BR/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/ru/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/zh_CN/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/share/locale/zh_TW/LC_MESSAGES/pcsxr.mo
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libBladeSio1.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgBladeSio1
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libNullSio1.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libDFCdrom.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgDFCdrom
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libDFInput.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgDFInput
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libDFNet.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgDFNet
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libDFSound.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgDFSound
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libDFXVideo.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgDFXVideo
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/libpeopsxgl.so
#borrar#rm -rf /usr/lib/x86_64-linux-gnu/games/psemu/cfgpeopsxgl
#borrar#rm -rf /usr/share/man/man1/pcsxr.1
#borrar#rm -rf /usr/share/doc/pcsxr/keys.txt
#borrar#rm -rf /usr/share/doc/pcsxr/tweaks.txt
#borrar#rm -rf /usr/share/doc/pcsxr/AUTHORS
#borrar#rm -rf /usr/share/doc/pcsxr/COPYING
#borrar#rm -rf /usr/share/doc/pcsxr/README

# Emulador e Icono
chmod a+o+x "$PREFIJO"/bin/pcsxr
echo
echo "Concede acceso para establecer el icono del menu"
echo
rm -rf /usr/share/pixmaps/pcsxr-icon.png
sudo cp "/tmp/src/pcsxr/gui/data/pixmaps/pcsxr.png" "/usr/share/pixmaps/pcsxr-icon.png"

if [ "$PREFIJO" = "/usr" ]; then

mv /usr/bin/pcsxr /usr/bin/pcsxr.real

# Crear el guión lanzador :
echo '#!/usr/bin/env bash

# Establecer Ruta :
PREFIJO='"$PREFIJO"'

# Borrar archivos anteriores :
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFInput"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFNet"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFSound"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
rm -rf "$HOME/.pcsxr/plugins/libBladeSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libDFCdrom.so"
rm -rf "$HOME/.pcsxr/plugins/libDFInput.so"
rm -rf "$HOME/.pcsxr/plugins/libDFNet.so"
rm -rf "$HOME/.pcsxr/plugins/libDFSound.so"
rm -rf "$HOME/.pcsxr/plugins/libDFXVideo.so"
rm -rf "$HOME/.pcsxr/plugins/libNullSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Enlazar Complementos
# Correspondientes a esta version :
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libBladeSio1.so"		"$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgDFCdrom"		"$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgDFInput"		"$HOME/.pcsxr/plugins/cfg/cfgDFInput"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgDFNet"			"$HOME/.pcsxr/plugins/cfg/cfgDFNet"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgDFSound"		"$HOME/.pcsxr/plugins/cfg/cfgDFSound"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgDFXVideo"	    	"$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/cfgpeopsxgl"		"$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libBladeSio1.so"		"$HOME/.pcsxr/plugins/libBladeSio1.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libDFCdrom.so"		"$HOME/.pcsxr/plugins/libDFCdrom.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libDFInput.so"		"$HOME/.pcsxr/plugins/libDFInput.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libDFNet.so"		"$HOME/.pcsxr/plugins/libDFNet.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libDFSound.so"		"$HOME/.pcsxr/plugins/libDFSound.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libDFXVideo.so"		"$HOME/.pcsxr/plugins/libDFXVideo.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libNullSio1.so"	        "$HOME/.pcsxr/plugins/libNullSio1.so"
ln -sf "/usr/lib/x86_64-linux-gnu/games/psemu/libpeopsxgl.so"	        "$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Iniciar Emulador
export PATH="$PREFIJO/bin/":$PATH
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PREFIJO/games/psemu/"
cd "$PREFIJO/bin"
SDL_AUDIODRIVER=pulse ./pcsxr.real "$@"
echo' | tee "/tmp/pcsxr"

mv /tmp/pcsxr /usr/bin/pcsxr
chmod a+o+x /usr/bin/pcsxr.real

#Crear Entrada para el Menú :
echo '[Desktop Entry]
Version=1.0
Type=Application
Name=PCSXR
GenericName=PlayStation Emulator
GenericName[ru_RU]=Эмулятор PlayStation
GenericName[zh_CN]=PlayStation 模拟器
GenericName[zh_TW]=PlayStation 模擬器
Comment=Sony PlayStation emulator
Comment[ru_RU]=Эмулятор Sony PlayStation
Comment[zh_CN]=Sony PlayStation 模拟器
Comment[zh_TW]=Sony PlayStation 模擬器
Comment[es_ES]=Emulador de Sony PlayStation 1
Comment[es_VE]=Emulador de Sony PlayStation 1
Exec=/usr/bin/pcsxr
Icon=pcsxr-icon
Categories=Game;' | sudo tee /usr/share/applications/pcsxr.desktop

echo
echo "Concede acceso de usuario a la entrada de menu"
echo
chmod a+o+x /usr/share/applications/pcsxr.desktop
chmod 777 /usr/bin/pcsxr

else
# Crear el guión lanzador :
echo '#!/usr/bin/env bash

# Establecer Ruta :
PREFIJO='"$PREFIJO"'

# Borrar archivos anteriores :
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFInput"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFNet"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFSound"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
rm -rf "$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
rm -rf "$HOME/.pcsxr/plugins/libBladeSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libDFCdrom.so"
rm -rf "$HOME/.pcsxr/plugins/libDFInput.so"
rm -rf "$HOME/.pcsxr/plugins/libDFNet.so"
rm -rf "$HOME/.pcsxr/plugins/libDFSound.so"
rm -rf "$HOME/.pcsxr/plugins/libDFXVideo.so"
rm -rf "$HOME/.pcsxr/plugins/libNullSio1.so"
rm -rf "$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Enlazar Complementos
# Correspondientes a esta version :
ln -sf "$PREFIJO/lib/games/psemu/cfgBladeSio1"		"$HOME/.pcsxr/plugins/cfg/cfgBladeSio1"
ln -sf "$PREFIJO/lib/games/psemu/cfgDFCdrom"		"$HOME/.pcsxr/plugins/cfg/cfgDFCdrom"
ln -sf "$PREFIJO/lib/games/psemu/cfgDFInput"		"$HOME/.pcsxr/plugins/cfg/cfgDFInput"
ln -sf "$PREFIJO/lib/games/psemu/cfgDFNet"		"$HOME/.pcsxr/plugins/cfg/cfgDFNet"
ln -sf "$PREFIJO/lib/games/psemu/cfgDFSound"		"$HOME/.pcsxr/plugins/cfg/cfgDFSound"
ln -sf "$PREFIJO/lib/games/psemu/cfgDFXVideo"	    	"$HOME/.pcsxr/plugins/cfg/cfgDFXVideo"
ln -sf "$PREFIJO/lib/games/psemu/cfgpeopsxgl"		"$HOME/.pcsxr/plugins/cfg/cfgpeopsxgl"
ln -sf "$PREFIJO/lib/games/psemu/libBladeSio1.so"	"$HOME/.pcsxr/plugins/libBladeSio1.so"
ln -sf "$PREFIJO/lib/games/psemu/libDFCdrom.so"		"$HOME/.pcsxr/plugins/libDFCdrom.so"
ln -sf "$PREFIJO/lib/games/psemu/libDFInput.so"		"$HOME/.pcsxr/plugins/libDFInput.so"
ln -sf "$PREFIJO/lib/games/psemu/libDFNet.so"		"$HOME/.pcsxr/plugins/libDFNet.so"
ln -sf "$PREFIJO/lib/games/psemu/libDFSound.so"		"$HOME/.pcsxr/plugins/libDFSound.so"
ln -sf "$PREFIJO/lib/games/psemu/libDFXVideo.so"	"$HOME/.pcsxr/plugins/libDFXVideo.so"
ln -sf "$PREFIJO/lib/games/psemu/libNullSio1.so"	"$HOME/.pcsxr/plugins/libNullSio1.so"
ln -sf "$PREFIJO/lib/games/psemu/libpeopsxgl.so"	"$HOME/.pcsxr/plugins/libpeopsxgl.so"

# Iniciar Emulador
export PATH="$PREFIJO/bin/":$PATH
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PREFIJO/games/psemu/"
cd "$PREFIJO/bin"
SDL_AUDIODRIVER=pulse ./pcsxr "$@"
echo' | tee "/tmp/pcsxr"

mv /tmp/pcsxr /usr/bin/pcsxr
chmod a+o+x /usr/bin/pcsxr

#Crear Entrada para el Menú :
echo '[Desktop Entry]
Version=1.0
Type=Application
Name=PCSXR
GenericName=PlayStation Emulator
GenericName[ru_RU]=Эмулятор PlayStation
GenericName[zh_CN]=PlayStation 模拟器
GenericName[zh_TW]=PlayStation 模擬器
Comment=Sony PlayStation emulator
Comment[ru_RU]=Эмулятор Sony PlayStation
Comment[zh_CN]=Sony PlayStation 模拟器
Comment[zh_TW]=Sony PlayStation 模擬器
Comment[es_ES]=Emulador de Sony PlayStation 1
Comment[es_VE]=Emulador de Sony PlayStation 1
Exec=/usr/bin/pcsxr
Icon=pcsxr-icon
Categories=Game;' | sudo tee /usr/share/applications/pcsxr.desktop

echo
echo "Concede acceso de usuario a la entrada de menu"
echo
chmod a+o+x /usr/share/applications/pcsxr.desktop
chmod 777 /usr/bin/pcsxr
fi
fi