#!/usr/bin/env bash

echo '
Autor ----------------> Inukaze ( Venezuela )
Sitio ----------------> https://goo.gl/ij6WqW
Correo-E -------------> bloginukaze@gmail.com
Licencia -------------> GPL 2

******* Inicio : Acerca de este Script ********
				  
    Es un sencillo MiniScript para Iniciar
    "dhewm3" (Motor de Doom3). en un equipo
    de recursos limitados.
    
    Si se detecta el uso del controlador
    de video nvidia. usar la herramienta
    "nvidia-settings" para cambiar la
    resolucion para mejorar el rendimiento

******** Fin : Acerca de este Script **********
'
sleep 3

Configuracion="$HOME/.config/dhewm3/base/dhewm.cfg"

#Doom3 Original
# r_modes	    ->	3=640x480 , 4=800x600 , 5=1024x768 , 6=1152x864 , 7=1280x1024 , 8=1600x1200
# r_aspectratio	    ->	0=4:3 (normal), 1=16:9 (standard widescreen), 2=16:10 (nonstandard).
# r_displayrefresh  ->	60, 70, 75, 80, 85

function Video(){

Tarjeta=$(lspci -v | grep "VGA" | cut -d " " -f05)

if [ "$Tarjeta" = "NVIDIA" ]; then
    Controlador=$(lspci -nnk | grep -i vga -A3 | grep 'in use' | cut -d " " -f05)
    if [ "$Controlador" = "nvidia" ]; then
	binario_ns=$(whereis -B "/usr/sbin" "/usr/local/sbin" "/sbin" "/usr/bin" "/usr/local/bin" "/bin" -b nvidia-settings | grep -i "nvidia-settings" | cut -d " " -f02)
	binario_xr=$(whereis -B "/usr/sbin" "/usr/local/sbin" "/sbin" "/usr/bin" "/usr/local/bin" "/bin" -b xrandr | grep -i "xrandr" | cut -d " " -f02)
	if test -x "$binario_ns"
	then
	    #echo "encontrado el ejecutable : nvidia-settings"
	    Cambiador="$binario_ns"
	else
	    #echo "no se encontro el ejecutable : nvidia-settings"
	    Cambiador="$binario_xr"
	fi
    fi    
fi

# Solucion de Resolucion
xrandr --current | grep current | awk '{print $8}' >> /tmp/Resolucion1
xrandr --current | grep current | awk '{print $10}' >> /tmp/Resolucion2
sed 's/.$//' /tmp/Resolucion2 >> /tmp/Resolucion3 && mv -f /tmp/Resolucion3 /tmp/Resolucion2
P1Resolucion=$(cat /tmp/Resolucion1)
P2Resolucion=$(cat /tmp/Resolucion2)
rm /tmp/Resolucion1 /tmp/Resolucion2
echo "$P1Resolucion"'x'"$P2Resolucion" >> Resolucion
Resolucion=$(cat Resolucion) ; export Resolucion
rm Resolucion
# Solucion de Resolucion

if test -f "$Configuracion"
then
PantallaCompleta=$(cat < "$Configuracion" | grep "seta r_fullscreen" | awk '{print $3}' | sed 's/["]//g')
ResolucionEnConfiguracion=$(cat < "$Configuracion" | grep "seta r_mode" | awk '{print $3}' | sed 's/["]//g')

    if [ "$PantallaCompleta" == "0" ]; then
	    echo "Iniciando en Modo : Ventana"
    fi
    
    if [ "$PantallaCompleta" == "1" ]; then
	    echo "Iniciando en Modo : Pantalla Completa"
	if [ "$Cambiador" == "$binario_ns" ]; then
	    case "$ResolucionEnConfiguracion" in
	    1) $Cambiador --assign CurrentMetaMode="400x300_75 +0+0"	    ;;
	    2) $Cambiador --assign CurrentMetaMode="512x384_75 +0+0"	    ;;
	    3) $Cambiador --assign CurrentMetaMode="640x480_75 +0+0"	    ;;
	    4) $Cambiador --assign CurrentMetaMode="800x600_75 +0+0"	    ;;
	    5) $Cambiador --assign CurrentMetaMode="1024x768_60 +0+0"	    ;;
	    6) $Cambiador --assign CurrentMetaMode="1152x864_60 +0+0"	    ;;
	    7) $Cambiador --assign CurrentMetaMode="1280x1024_60 +0+0"	    ;;
	    8) $Cambiador --assign CurrentMetaMode="1600x1200_60 +0+0"	    ;;
	    *)  echo -e 'Problablemente estes usando los valores de las variables \n "r_customHeight" & "r_customWidth"'	;;
	    esac
	fi    
	if [ "$Cambiador" == "$binario_xr" ]; then
	    echo
	    case "$ResolucionEnConfiguracion" in
	    1) $Cambiador -s 400x300		;;
	    2) $Cambiador -s 512x384		;;
	    3) $Cambiador -s 640x480		;;
	    4) $Cambiador -s 800x600 -r 67	;;  #65=66=70, 67=75
	    5) $Cambiador -s 1024x768 -r 59	;;  #57=60, 58=70, 59=75
	    6) $Cambiador -s 1152x864		;;
	    7) $Cambiador -s 1280x1024		;;
	    8) $Cambiador -s 1600x1200		;; 
	    *)  echo -e 'Problablemente estes usando los valores de las variables \n "r_customHeight" & "r_customWidth"'	;;
	    esac
	fi
    fi
fi
}


Video	#   Me falta agregar que detecte si se esta usando por ejemplo otra pantalla como la de un TV
	#   Cambiar la resolucion a la misma que se cambia la del juego
	#   al salir volver activar el TV por algun motivo lo desactiva al cambiar la resolucion   

if test -x "$PWD/.dhewm3.x64"
then
#VALORVARIABLE#    echo
#VALORVARIABLE#    echo "Configuracion=$Configuracion"
#VALORVARIABLE#    echo "ResolucionGuardada=$Resolucion"
#VALORVARIABLE#    echo
#VALORVARIABLE#    echo "PantallaCompleta=$PantallaCompleta"
#VALORVARIABLE#    echo 'Pantalla Completa | 0=NO , 1=SI'
#VALORVARIABLE#    echo "Resolucion Del Juego=$ResolucionEnConfiguracion"
#VALORVARIABLE#    echo
#VALORVARIABLE#    echo '1=400x300  , 2=512x384  , 3=640x480   , 4=800x600'
#VALORVARIABLE#    echo '5=1024x768 , 6=1152x864 , 7=1280x1024 , 8=1600x1200'
#VALORVARIABLE#    echo
#VALORVARIABLE#    echo "Cambiador de Resolucion=$Cambiador"
#VALORVARIABLE#    echo
    ./.dhewm3.x64 "$@" &
    sleep 1 && killall -9 .dhewm3.x64
	    if [ "$Cambiador" = "$binario_ns" ]; then
	          $Cambiador --assign CurrentMetaMode="$Resolucion +0+0"
	    fi

	    if [ "$Cambiador" = "$binario_xr" ]; then
		  $Cambiador -s "$Resolucion"
	    fi
    ./dhewm3 "$@"
fi


if [ "$Cambiador" = "$binario_ns" ]; then
      $Cambiador --assign CurrentMetaMode="$Resolucion +0+0"
fi

if [ "$Cambiador" = "$binario_xr" ]; then
      $Cambiador -s "$Resolucion"
fi