#!/bin/sh
echo
echo "iptables -> Reiniciando Politicas Predeterminadas"
echo "Para ello se usan los siguientes comandos :"
echo
sudo iptables -P INPUT ACCEPT ; echo "sudo iptables -P INPUT ACCEPT"
sudo iptables -P FORWARD ACCEPT ; echo "sudo iptables -P FORWARD ACCEPT"
sudo iptables -P OUTPUT ACCEPT ; echo "sudo iptables -P OUTPUT ACCEPT"
sudo iptables -t nat -P PREROUTING ACCEPT ; echo "sudo iptables -t nat -P
PREROUTING ACCEPT"
sudo iptables -t nat -P POSTROUTING ACCEPT ; echo "sudo iptables -t nat -P
POSTROUTING ACCEPT"
sudo iptables -t nat -P OUTPUT ACCEPT ; echo "sudo iptables -t nat -P OUTPUT
ACCEPT"
sudo iptables -t mangle -P PREROUTING ACCEPT ; echo "sudo iptables -t mangle
-P PREROUTING ACCEPT"
sudo iptables -t mangle -P OUTPUT ACCEPT ; echo "sudo iptables -t mangle -P
-OUTPUT ACCEPT"

echo
echo "iptables -> Limpiando todas las Reglas"
echo "iptables -> Borrando todas las cadenas No-Predeterminadas"
echo "Para ello se usan los siguientes comandos :"
echo
sudo iptables -F ; echo "sudo iptables -F"
sudo iptables -X ; echo "sudo iptables -X"
sudo iptables -t nat -F ; echo "sudo iptables -t nat -F"
sudo iptables -t nat -X ; echo "sudo iptables -t nat -X"
sudo iptables -t mangle -F ; echo "sudo iptables -t mangle -F"
sudo iptables -t mangle -X ; echo "sudo iptables -t mangle -X"