#!/usr/bin/env playonlinux-bash
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
export WINEPREFIX="/home/inukaze/.PlayOnLinux//wineprefix/Steam"
export WINEDEBUG="-all"
ScriptID=Steam
cd "/home/inukaze/.PlayOnLinux//wineprefix/Steam/drive_c/./Program Files/Steam"
POL_Wine Steam.exe -no-dwrite -no-cef-sandbox "$@" &

# Inukaze :
# Solucion de Resolucion
xrandr --current | grep current | awk '{print $8}' >> /tmp/Resolucion1
xrandr --current | grep current | awk '{print $10}' >> /tmp/Resolucion2
sed 's/.$//' /tmp/Resolucion2 >> /tmp/Resolucion3 && mv -f /tmp/Resolucion3 /tmp/Resolucion2
P1Resolucion=$(cat /tmp/Resolucion1)
P2Resolucion=$(cat /tmp/Resolucion2)
rm /tmp/Resolucion1 /tmp/Resolucion2
echo "$P1Resolucion"'x'"$P2Resolucion" >> Resolucion
Resolucion=$(cat Resolucion) ; export Resolucion
rm Resolucion
# Solucion de Resolucion

# Detectar si es una tarjeta de video NVIDIA y se se usa "nvidia-settings"
Tarjeta=$(lspci -v | grep "VGA" | cut -d " " -f05)

if [ "$Tarjeta" = "NVIDIA" ]; then
    Controlador=$(lspci -nnk | grep -i vga -A3 | grep 'in use' | cut -d " " -f05)
    if [ "$Controlador" = "nvidia" ]; then
	binario_ns=$(whereis -B "/usr/sbin" "/usr/local/sbin" "/sbin" "/usr/bin" "/usr/local/bin" "/bin" -b nvidia-settings | grep -i "nvidia-settings" | cut -d " " -f02)
	binario_xr=$(whereis -B "/usr/sbin" "/usr/local/sbin" "/sbin" "/usr/bin" "/usr/local/bin" "/bin" -b xrandr | grep -i "xrandr" | cut -d " " -f02)
	if test -x "$binario_ns"
	then
	    Cambiador="$binario_ns"
	else
	    Cambiador="$binario_xr"
	fi
    fi    
fi

# Esperar que "Plants Vs Zombies GOTY" Inicie
until pids=$(pidof PlantsVsZombies.exe)
do   
    sleep 1
done

# Esperar que se haya iniciado "Plants Vs Zombies GOTY"
for pid in $pids
do
    if [ "$Cambiador" == "$binario_ns" ]; then
         "$Cambiador" --assign CurrentMetaMode="800x600_75 +0+0" # Cambiar la resolucion a 800x600 con tasa de refresco 75
    fi
    
    if [ "$Cambiador" == "$binario_xr" ]; then
	 "$Cambiador" -s 800x600 -r 51 # Cambiar la resolucion a 800x600 con tasa de refresco 75 (el 51 puede variar)
    fi
    
    unset pids # Vaciar la variable "pids"
done

# Esperar que "Deus EX GOTYE" Inicie
until pids=$(pidof DeusEx.exe)
do   
    sleep 1
done

# Esperar que se haya iniciado "Deus EX GOTYE"
for pid in $pids
do
    if [ "$Cambiador" == "$binario_ns" ]; then
         "$Cambiador" --assign CurrentMetaMode="800x600_75 +0+0" # Cambiar la resolucion a 800x600 con tasa de refresco 75
    fi
    
    if [ "$Cambiador" == "$binario_xr" ]; then
	 "$Cambiador" -s 800x600 -r 51 # Cambiar la resolucion a 800x600 con tasa de refresco 75 (el 51 puede variar)
    fi
    
    unset pids # Vaciar la variable "pids"
done


# Esperar que "Castlevania : Lord Of Shadows - Mirror Of Fate" Inicie
until pids=$(pidof CMOF.exe)
do   
    sleep 1
done

# Esperar que se haya iniciado "Castlevania : Lord Of Shadows - Mirror Of Fate"
for pid in $pids
do
    if [ "$Cambiador" == "$binario_ns" ]; then
         "$Cambiador" --assign CurrentMetaMode="800x600_75 +0+0" # Cambiar la resolucion a 800x600 con tasa de refresco 75
    fi
    
    if [ "$Cambiador" == "$binario_xr" ]; then
	 "$Cambiador" -s 800x600 -r 51 # Cambiar la resolucion a 800x600 con tasa de refresco 75 (el 51 puede variar)
    fi
    
    unset pids # Vaciar la variable "pids"
done