#!/bin/sh
#!/bin/bash
# 
# Autor	:	Inukaze ( Venezuela )
# Sitio		:	http://inukaze.wordpResolucions.com
# Correo-E	:	bloginukaze@gmail.com
# Licensia	:	GPL 3
#
# Acerca de este Script	:	
#
# Yo intento escribir Scripts compatibles con
# Sistemas Operativos Unix & Posix , y cualquier
# Sistema Operativo que soporte versiones de la API
# conocida como "Wine" o "WineHQ" para poder ejecutar
# software de Microsoft Windows , sin necesidad de su
# sistema operativo , y crear paquetes autocontenidos
# para sistemas operativos como por ejemplo :
# Linux , FreeBSD , OpenSolaris 
# Unix  , BSD	  , Solaris		, MacOS

# Usando versiones pre-compiladas , para arquitecturas
# como x86 & x86_64 (32 Bits & 64 Bits ) con versiones
# Especificas de Wine/WineHQ y los Arquitecturaivos oficiales
# para "Windows" para una mayor compatibilidad usando
# los requisitos de Sistema Originales y que esto pueda
# ser aprovechado , por Juegos , Programas , Software
# Ahora apartir de aqui comienza mi Script :

xmessage -timeout 13 "Se Esta Configurando El Software" &

# Definir el directorio actual , como el principal
# del juego o programa
RUTA=""$( cd -P "$( dirname "$" )" && pwd )""

# Obtener el nombre del nucleo del sistema
Nucleo=$(uname -s)

if		[ $Nucleo = "Darwin" ]; then
		Nucleo=mac
elif		[ $Nucleo = "Linux" ]; then
		Nucleo=linux
else
		echo "Sistema Operativo NO SOPORTADO"
fi

# Determinando la arquitectura de la maquina
Arquitectura=$(uname -m)

if	       [ $Arquitectura = "i386" ]; then
			PATH="$PWD/wine/$Nucleo/x86/bin:$PATH"
			export WINESERVER="$PWD/wine/$Nucleo/x86/bin/wineserver"
			export WINELOADER="$PWD/wine/$Nucleo/x86/bin/wine"
			export WINEPREFIX="$PWD/wine/data"
			export WINEDEBUG=-all
			Arquitectura="32 Bits"
	elif	[ $Arquitectura = "i486" ]; then
			PATH="$PWD/wine/$Nucleo/x86/bin:$PATH"
			export WINESERVER="$PWD/wine/$Nucleo/x86/bin/wineserver"
			export WINELOADER="$PWD/wine/$Nucleo/x86/bin/wine"
			export WINEPREFIX="$PWD/wine/data"
			export WINEDEBUG=-all
			Arquitectura="32 Bits"
	elif	[ $Arquitectura = "i586" ]; then
			PATH="$PWD/wine/$Nucleo/x86/bin:$PATH"
			export WINESERVER="$PWD/wine/$Nucleo/x86/bin/wineserver"
			export WINELOADER="$PWD/wine/$Nucleo/x86/bin/wine"
			export WINEPREFIX="$PWD/wine/data"
			export WINEDEBUG=-all
			Arquitectura="32 Bits"
	elif	[ $Arquitectura = "i686" ]; then
			PATH="$PWD/wine/$Nucleo/x86/bin:$PATH"
			export WINESERVER="$PWD/wine/$Nucleo/x86/bin/wineserver"
			export WINELOADER="$PWD/wine/$Nucleo/x86/bin/wine"
			export WINEPREFIX="$PWD/wine/data"
			export WINEDEBUG=-all
			Arquitectura="32 Bits"
         elif [ $Arquitectura = "x86_64" ]; then
			export WINESERVER="$PWD/wine/$Nucleo/x86_64/bin/wineserver"
			export WINELOADER="$PWD/wine/$Nucleo/x86_64/bin/wine"
			export WINEPREFIX="$PWD/wine/data"
			export WINEDEBUG=-all
			Arquitectura="64 Bits"
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dplaysvr.exe
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPLAYSVR.exe
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dplayx.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPLAYX.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpmodemx.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPMODEMX.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnet.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPNET.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnhpast.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPNHPAST.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnlobby.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPNLOBBY.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnsvr.exe
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPNSVR.exe
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpwsockx.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/DPWSOCKX.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dplaysvr.exe
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3d8.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3d8thk.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3d9.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dim.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dim700.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dpmesh.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dramp.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3drm.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_24.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_25.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_26.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_27.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_28.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_29.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_30.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_31.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_32.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_33.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_34.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_35.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dx9_36.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/D3DX9_37.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/d3dxof.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dciman32.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/ddrawex.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/devenum.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dinput.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dinput8.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmband.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmcompos.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmime.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmloader.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmscript.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmstyle.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmsynth.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dmusic.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dnsapi.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dplay.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnaddr.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnmodem.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dsound.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dsound3d.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dswave.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dxdiagn.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/mscoree.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/msdmo.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/qcap.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/quartz.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/streamci.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpnhupnp.dll
			rm -rf "$RUTA"/wine/data/drive_c/windows/syswow64/dpserial.dll
			mkdir -p "$RUTA"/wine/data/drive_c/windows/syswow64
			cd "$RUTA"/wine/data/drive_c/software/directx
			cp -rf *.* "$RUTA"/wine/data/drive_c/windows/syswow64
	else
		echo "Arquitectura NO SOPORTADA"
fi 

# Borrar Toda Configuracion Previa WINE:
rm -rf "$RUTA/wine/data/drive_c/users"
rm -rf "$RUTA/wine/data/drive_c/windows"
rm -rf "$RUTA/wine/data/Program Files (x86)"
rm -rf "$RUTA/wine/data/drive_c/Archivos de programa"
rm -rf "$RUTA/wine/data/drive_c/Program Files (x86)"
rm -rf "$RUTA/wine/data/system.reg"
rm -rf "$RUTA/wine/data/user.reg"
rm -rf "$RUTA/wine/data/userdef.reg"
rm -rf "$RUTA/wine/data/dosdevices"
rm -rf "$RUTA/wine/data/.update-timestamp"
rm -rf "$RUTA/wine/.DS_Store"
rm -rf "$RUTA/wine/linux/.DS_Store"
rm -rf "$RUTA/wine/linux/x86/.DS_Store"
rm -rf "$RUTA/wine/linux/x86_64/.DS_Store"
rm -rf "$RUTA/wine/linux/x86/bin/.DS_Store"
rm -rf "$RUTA/wine/linux/x86_64/bin/.DS_Store"
rm -rf "$RUTA/wine/mac/.DS_Store"
rm -rf "$RUTA/wine/mac/x86/.DS_Store"
rm -rf "$RUTA/wine/mac/x86_64/.DS_Store"
rm -rf "$RUTA/wine/mac/x86/bin/.DS_Store"
rm -rf "$RUTA/wine/mac/x86_64/bin/.DS_Store"
rm -rf "$RUTA"/wine/data/cachedmetrics.\:0

# Copiar Arquitecturaivos de DirectX & DirectPlay (Son nativos de Windows XP)
mkdir -p "$RUTA"/wine/data/drive_c/Escritorio
mkdir -p "$RUTA"/wine/data/drive_c/windows/system32
cd "$RUTA"/arreglos/windows/system32/
cp -rf *.* "$RUTA"/wine/data/drive_c/windows/system32

## Biblioteca Excluida Debido A
## A que produce un error interno de Wine :
#EIDW#regsvr32 mscoree.dll

cd "$RUTA"/wine/data/drive_c/windows/system32/
# Agregar valoResolucion de DirectX & DirectPlay al Registro
# - Estos son de DirectPlay
echo "REGEDIT4" >> dp.reg
echo "" >> dp.reg
echo "[HKEY_CURRENT_USER\Software\Wine\DllOverrides]" >> dp.reg
echo '"actmovie.exe"="native"' >> dp.reg
echo '"advapi32.dll"="native"' >> dp.reg
echo '"apphelp.dll"="native"' >> dp.reg
echo '"comctl32.dll"="native"' >> dp.reg
echo '"comres.dll"="native"' >> dp.reg
echo '"crypt32.dll"="native"' >> dp.reg
echo '"d3dim.dll"="native"' >> dp.reg
echo '"dciman32.dll"="native"' >> dp.reg
echo '"dnsapi.dll"="native"' >> dp.reg
echo '"dplay.dll"="native"' >> dp.reg
echo '"dplaysvr.exe"="native"' >> dp.reg
echo '"dpmodemx.dll"="native"' >> dp.reg
echo '"dpnaddr.dll"="native"' >> dp.reg
echo '"dpnlobby.dll"="native"' >> dp.reg
echo '"dpnsvr.exe"="native"' >> dp.reg
echo '"dpserial.dll"="native"' >> dp.reg
echo '"dpwsock.dll"="native"' >> dp.reg
echo '"dpwsockx.dll"="native"' >> dp.reg
echo '"dsound.vxd"="native"' >> dp.reg
echo '"dsound3d.dll"="native"' >> dp.reg
echo '"gdi32.dll"="native"' >> dp.reg
echo '"hid.dll"="native"' >> dp.reg
echo '"imagehlp.dll"="native"' >> dp.reg
echo '"imm32.dll"="native"' >> dp.reg
echo '"iphlpapi.dll"="native"' >> dp.reg
echo '"ir32_32.dll"="native"' >> dp.reg
echo '"kernel32.dll"="native"' >> dp.reg
echo '"ksuser.dll"="native"' >> dp.reg
echo '"lpk.dll"="native"' >> dp.reg
echo '"mciavi.drv"="native"' >> dp.reg
echo '"mciavi32.dll"="native"' >> dp.reg
echo '"mcicda.dll"="native"' >> dp.reg
echo '"mciole16.dll"="native"' >> dp.reg
echo '"mciole32.dll"="native"' >> dp.reg
echo '"mciqtz.drv"="native"' >> dp.reg
echo '"mciqtz32.dll"="native"' >> dp.reg
echo '"mciseq.dll"="native"' >> dp.reg
echo '"mciseq.drv"="native"' >> dp.reg
echo '"mciwave.dll"="native"' >> dp.reg
echo '"mciwave.drv"="native"' >> dp.reg
echo '"midimap.dll"="native"' >> dp.reg
echo '"mplay32.exe"="native"' >> dp.reg
echo '"msacm32.dll"="native"' >> dp.reg
echo '"msacm32.drv"="native"' >> dp.reg
echo '"msasn1.dll"="native"' >> dp.reg
echo '"msaud32.acm"="native"' >> dp.reg
echo '"msctfime.ime"="native"' >> dp.reg
echo '"MSCTFIME.IME"="native"' >> dp.reg
echo '"msdmo.dll"="native"' >> dp.reg
echo '"msrle32.dll"="native"' >> dp.reg
echo '"mstime.dll"="native"' >> dp.reg
echo '"msvcrt.dll"="native"' >> dp.reg
echo '"msvfw32.dll"="native"' >> dp.reg
echo '"msvidc32.dll"="native"' >> dp.reg
echo '"mswsock.dll"="native"' >> dp.reg
echo '"netapi32.dll"="native"' >> dp.reg
echo '"ntdll.dll"="native"' >> dp.reg
echo '"ntkrnlpa.exe"="native"' >> dp.reg
echo '"quartz.vxd"="native"' >> dp.reg
echo '"rasadhlp.dll"="native"' >> dp.reg
echo '"rasapi32.dll"="native"' >> dp.reg
echo '"rasman.dll"="native"' >> dp.reg
echo '"rtutils.dll"="native"' >> dp.reg
echo '"secur32.dll"="native"' >> dp.reg
echo '"shlwapi.dll"="native"' >> dp.reg
echo '"streamci.dll"="native"' >> dp.reg
echo '"tapi32.dll"="native"' >> dp.reg
echo '"timer.drv"="native"' >> dp.reg
echo '"user32.dll"="native"' >> dp.reg
echo '"usp10.dll"="native"' >> dp.reg
echo '"uxtheme.dll"="native"' >> dp.reg
echo '"version.dll"="native"' >> dp.reg
echo '"vga.dll"="native"' >> dp.reg
echo '"vga256.dll"="native"' >> dp.reg
echo '"vga64k.dll"="native"' >> dp.reg
echo '"vidx16.dll"="native"' >> dp.reg
echo '"wdmaud.drv"="native"' >> dp.reg
echo '"winmm.dll"="native"' >> dp.reg
echo '"wldap32.dll"="native"' >> dp.reg
echo '"wmploc.dll"="native"' >> dp.reg
echo '"ws2_32.dll"="native"' >> dp.reg
echo '"ws2help.dll"="native"' >> dp.reg
echo '"wsock32.dll"="native"' >> dp.reg
regedit -S dp.reg
rm dp.reg

# Registrando Librerias de Indeo
mkdir -p "$RUTA"/wine/data/drive_c/windows/system32
rm -rf "$RUTA"/wine/data/drive_c/windows/system32/msrle32.dll
rm -rf "$RUTA"/wine/data/drive_c/windows/system32/msvidc32.dll

cp "$RUTA"/arreglos/windows/system32/ir50_32.dll "$RUTA"/wine/data/drive_c/windows/system32/
cp "$RUTA"/arreglos/windows/system32/msaud32.acm "$RUTA"/wine/data/drive_c/windows/system32/
cp "$RUTA"/arreglos/windows/system32/msrle32.dll "$RUTA"/wine/data/drive_c/windows/system32/
cp "$RUTA"/arreglos/windows/system32/midimap.dll "$RUTA"/wine/data/drive_c/windows/system32/
cp "$RUTA"/arreglos/windows/system32/msvidc32.dll "$RUTA"/wine/data/drive_c/windows/system32/

cd "$RUTA"/wine/data/drive_c/windows/system32/

#### Agregados para Intentar Ver Videos : ###
#### 	Desde el Ejecutable comm2.exe	  ###
regsvr32 amstream.dll
regsvr32 avifil32.dll
regsvr32 clbcatq.dll
regsvr32 comdlg32.dll
regsvr32 datime.dll
regsvr32 ddraw.dll
regsvr32 ddrawex.dll
regsvr32 devenum.dll
regsvr32 dinput.dll
regsvr32 dinput8.dll
regsvr32 dmband.dll
regsvr32 dmcompos.dll
regsvr32 dmime.dll
regsvr32 dmloader.dll
regsvr32 dmscript.dll
regsvr32 dmstyle.dll
regsvr32 dmsynth.dll
regsvr32 dmusic.dll
regsvr32 dplayx.dll
regsvr32 dpnet.dll
regsvr32 dpnhpast.dll
regsvr32 dpnmodem.dll
regsvr32 dpnwsock.dll
regsvr32 dpvacm.dll
regsvr32 dpvoice.dll
regsvr32 dpvvox.dll
regsvr32 dsdmo.dll
regsvr32 dsdmoprp.dll
regsvr32 dsound.dll
regsvr32 dswave.dll
regsvr32 dxdiagn.dll
regsvr32 hnetcfg.dll
regsvr32 iac25_32.ax
regsvr32 ir41_32.ax
regsvr32 ir50_32.dll
regsvr32 mci32.ocx
regsvr32 msctf.dll
regsvr32 MSCTF.dll
regsvr32 MSIMTF.dll
regsvr32 ole32.dll
regsvr32 oleaut32.dll
regsvr32 quartz.dll
regsvr32 rpcrt4.dll
regsvr32 rsaenh.dll
regsvr32 shell32.dll
regsvr32 urlmon..dll
regsvr32 w32time.dll
regsvr32 wintrust.dll
regsvr32 wmpasf.dll

##########################:


wine regedit -s "$RUTA"/arreglos/DirectX.reg
wine regedit -s "$RUTA"/arreglos/software.reg
wine regedit -s "$RUTA"/arreglos/Videos.reg
wine regedit -s "$RUTA"/arreglos/"$Nucleo"_video.reg
wine regedit -s "$RUTA"/arreglos/"$Nucleo"_sonido.reg
# Fin del Arreglo para Videos con Indeo

cd "$RUTA"/arreglos
#wine "K-Lite_Codec_Pack_980_Full.exe"

# Detectar el Directorio "Escritorio"
# Dentro del usuario actual

cd $HOME
if [ -e Desktop ]; then cd Desktop; DirectorioEscritorio=$HOME/Desktop; fi
if [ -e Escritorio ]; then cd Escritorio; DirectorioEscritorio=$HOME/Escritorio; fi

if [ ! -e $DirectorioEscritorio/Wine ]; then
mkdir -p $DirectorioEscritorio/Wine
cd $DirectorioEscritorio/Wine
fi

if [ -e $DirectorioEscritorio/Wine ]; then
cd $DirectorioEscritorio/Wine
fi

# Escribir Los Archivos de "Enlace(s)"
# Necesarios dentro de la Carpeta "$HOME/$DirectorioEscritorio/Wine"

# Primero Borrar cualquier archivo Anterior
# De Escritorio , para Evitar Conflictos y no crear archivos innecesarios.

if [ -f "Commandos 2.desktop" ]; then rm -rf "Commandos 2.desktop"; fi
touch "Commandos 2.desktop"
echo "#!/usr/bin/env xdg-open"  >> "Commandos 2.desktop"
echo "" >> "Commandos 2.desktop"
echo '[Desktop Entry]' >> "Commandos 2.desktop"
echo "Version=1.0" >> "Commandos 2.desktop"
echo "Type=Application" >> "Commandos 2.desktop"
echo "Terminal=false" >> "Commandos 2.desktop"
echo 'Exec=sh "'$RUTA'"/.Lanzar' >> "Commandos 2.desktop"
echo "Name=Commandos 2" >> "Commandos 2.desktop"
echo "Icon=$RUTA/.comm2.png" >> "Commandos 2.desktop"
echo "Path=$RUTA" >> "Commandos 2.desktop"
echo "StartupNotify=true" >> "Commandos 2.desktop"
echo "X-KDE-SubstituteUID=false" >> "Commandos 2.desktop"

# Marcar como de Confianza (Dar Permiso de Ejecucion):
chmod a+x "Commandos 2.desktop"

xmessage -timeout 3 "Se Ha Configurado Exitosamente"
