#!/bin/bash
#
#
#
FECHA=$(date +"%Y-%m-%d")
HORA=$(date +"%r")
ADC="/etc/resolv.conf"

sudo echo -e '\nInukaze , Configurador de : '"$ADC"'\n' ; \
echo -e "Si existe el archivo $ADC\nSe creara la copia : $ADC.$FECHA.$HORA\n" ; \
echo -e "Este Script Reemplaza los DNS Por los siguientes :\nIP OpenDNS 1 : 208.67.220.220\nIP OpenDNS 2 : 208.67.222.222\nIP Enrutador : 192.168.1.1\n"
if test -f $ADC
	then
		sudo cp "$ADC" "$ADC.$FECHA.$HORA"
	else
		echo "No existe $ADC , Se creara uno nuevo"
fi ; \

echo '# '"$ADC"'
# Generated by NetworkManager
nameserver 192.168.1.1
nameserver 208.67.220.220
nameserver 208.67.222.222' | sudo tee "$ADC"
